const planets=[
['mercury','Mercury','Terrestrial planet','0.39 AU','4,879 km','59 Earth days','88 Earth days','−180 to 430°C','0','The smallest and innermost planet, orbiting closer to the Sun than any other world.','Mercury is a small, rocky world with a heavily cratered surface. With almost no atmosphere to trap heat, its temperatures swing dramatically between its long day and night.','A solar day on Mercury lasts 176 Earth days — twice as long as its year.','Water ice persists in permanently shadowed craters near its poles.'],
['venus','Venus','Terrestrial planet','0.72 AU','12,104 km','243 Earth days','225 Earth days','465°C average','0','A cloud-covered world whose dense atmosphere makes it the hottest planet in the Solar System.','Venus is similar in size to Earth but is wrapped in a dense carbon-dioxide atmosphere. Its runaway greenhouse effect creates crushing pressure and extraordinary surface heat.','Venus spins in the opposite direction to most planets.','A Venus day is longer than a Venus year.'],
['earth','Earth','Terrestrial planet','1.00 AU','12,756 km','24 hours','365.25 days','15°C average','1','Our ocean world — the only place currently known to support life.','Earth is a dynamic rocky planet with liquid surface water, a nitrogen-oxygen atmosphere and a protective magnetic field. It is the third world from the Sun.','About 71% of Earth’s surface is covered by ocean.','Its magnetic field helps deflect charged particles from the solar wind.'],
['mars','Mars','Terrestrial planet','1.52 AU','6,792 km','24.6 hours','687 Earth days','−63°C average','2','The Red Planet is a cold desert world, sculpted by giant volcanoes and ancient waterways.','Mars has a thin atmosphere and a rust-red surface coloured by iron-rich minerals. Robotic missions are exploring evidence that water once flowed across this neighbouring world.','Olympus Mons is the largest volcano known in the Solar System.','Mars has seasons because its axis is tilted, much like Earth’s.'],
['jupiter','Jupiter','Gas giant','5.20 AU','142,984 km','9.9 hours','11.86 Earth years','−110°C (cloud tops)','95 known','The largest planet, a banded gas giant with immense storms and a powerful magnetic field.','Jupiter is primarily hydrogen and helium. Its swirling cloud bands and Great Red Spot make it instantly recognisable, while its many moons form a miniature planetary system.','The Great Red Spot is a vast storm wider than Earth.','Jupiter’s magnetic field is the strongest of any planet.'],
['saturn','Saturn','Gas giant','9.58 AU','120,536 km','10.7 hours','29.45 Earth years','−140°C (cloud tops)','274 known','A pale gas giant encircled by the Solar System’s most spectacular ring system.','Saturn’s bright rings are made of countless fragments of ice, rock and dust. Though it is nearly as large as Jupiter, it has the lowest density of any planet.','Saturn would float in water if there were an ocean large enough.','Its rings are astonishingly thin compared with their enormous width.'],
['uranus','Uranus','Ice giant','19.2 AU','51,118 km','17.2 hours','84 Earth years','−195°C average','28 known','A blue-green ice giant that rolls around the Sun on its side.','Uranus contains water, methane and ammonia fluids above a small rocky core. Its unusual tilt gives the planet extreme seasons lasting decades.','Uranus rotates on its side, with an axial tilt of about 98 degrees.','Methane in its atmosphere absorbs red light, giving Uranus its blue-green colour.'],
['neptune','Neptune','Ice giant','30.1 AU','49,528 km','16.1 hours','164.8 Earth years','−200°C average','16 known','A distant, deep-blue ice giant with the fastest winds measured in the Solar System.','Neptune is the outermost planet. It has a dark, dynamic atmosphere powered by internal heat, despite receiving little sunlight at its great distance.','Neptune’s winds can exceed 2,000 km/h.','It completed its first full orbit since discovery in 2011.'],
['pluto','Pluto','Dwarf planet','39.5 AU','2,377 km','6.4 Earth days','248 Earth years','−225°C average','5 known','A complex dwarf planet in the Kuiper Belt, beyond the eight major planets.','Pluto is a small icy world with mountains, glaciers and a heart-shaped plain. It was reclassified as a dwarf planet in 2006, but remains a richly varied destination.','Pluto and its largest moon, Charon, orbit a shared point in space.','New Horizons revealed active geology during its 2015 flyby.']
].map(([id,name,type,distance,diameter,day,year,temp,moons,description,overview,...facts])=>({id,name,type,distance,diameter,day,year,temp,moons,description,overview,facts}));
const $=s=>document.querySelector(s),tabs=$('#planet-tabs'),visual=$('#planet-visual'),dialog=$('#planet-dialog');let index=0,lastFocused;
tabs.innerHTML=planets.map((p,i)=>`<button class="planet-tab" role="tab" id="tab-${p.id}" aria-selected="${i===0}" aria-controls="planet-name" tabindex="${i===0?0:-1}" data-index="${i}"><span class="tab-dot ${p.id}"></span><span class="tab-label"><strong>${p.name}</strong><small>${p.distance}</small></span></button>`).join('');
function dialogContent(){const p=planets[index],facts=[['Diameter',p.diameter],['Day length',p.day],['Year length',p.year],['Temperature',p.temp],['Moons',p.moons],['Distance',p.distance]];$('#dialog-number').textContent=`${String(index+1).padStart(2,'0')} · ${p.type}`;$('#dialog-distance').textContent=`${p.distance} from the Sun`;$('#dialog-name').textContent=p.name;$('#dialog-overview').textContent=p.overview;$('#fact-grid').innerHTML=facts.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('');$('#interesting-list').innerHTML=p.facts.map(x=>`<li>${x}</li>`).join('')}
function setPlanet(i,focus=false){index=(i+planets.length)%planets.length;const p=planets[index];visual.className=`planet ${p.id}`;visual.setAttribute('aria-label',`Visual representation of ${p.name}`);$('#planet-type').textContent=`${String(index+1).padStart(2,'0')} · ${p.type}`;$('#planet-count').textContent=`${String(index+1).padStart(2,'0')} / 09`;$('#planet-name').textContent=p.name;$('#planet-description').textContent=p.description;$('#open-details').innerHTML=`Explore ${p.name} <span aria-hidden="true">↗</span>`;document.querySelectorAll('.planet-tab').forEach((t,n)=>{t.setAttribute('aria-selected',n===index);t.tabIndex=n===index?0:-1});if(focus)document.querySelector(`.planet-tab[data-index="${index}"]`).focus();if(dialog.open)dialogContent()}
function openDialog(){lastFocused=document.activeElement;dialogContent();dialog.showModal();$('#close-details').focus()}function closeDialog(){dialog.close();lastFocused?.focus()}
tabs.addEventListener('click',e=>{const t=e.target.closest('.planet-tab');if(t)setPlanet(+t.dataset.index)});tabs.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();setPlanet(e.key==='Home'?0:e.key==='End'?8:index+(e.key==='ArrowRight'?1:-1),true)});$('#previous').onclick=()=>setPlanet(index-1);$('#next').onclick=()=>setPlanet(index+1);$('#dialog-previous').onclick=()=>setPlanet(index-1);$('#dialog-next').onclick=()=>setPlanet(index+1);$('#open-details').onclick=openDialog;$('#close-details').onclick=closeDialog;dialog.addEventListener('click',e=>{if(e.target===dialog)closeDialog()});dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog()});document.addEventListener('keydown',e=>{if(dialog.open||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(e.key==='ArrowRight')setPlanet(index+1);if(e.key==='ArrowLeft')setPlanet(index-1)});
